#!/usr/bin/env python3

import subprocess as sp
import sys
from pathlib import Path
import os

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))


args = [
  SCRIPT_DIR + '/buildp',
  '--run'
]

args.extend(sys.argv[1:])
sp.run(" ".join(args), shell=True)
